import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  manifest: "/manifest.json",
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const viewport = {
  themeColor: "#3367D6",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
